name: GitHub Actions - Workflow run branches
run-name: Running - Workflow run branches
on:
  workflow_run:
    workflows: [GitHub Actions - Trigger 1]
    branches: [main]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Workflow que foi trigado"
