name: GitHub Actions - Dependency General
run-name: Running - ${{ github.event_name }} - ${{ github.workflow }}
on:
  push:
    branches:
      - main
      - develop
    # branches-ignore:
    # - 'release/**'
    # paths:
    #   - "**.txt"
env:
  variavel: Teste Env
jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário DEPENDENCY WORKFLOW"

  test-push-2:
    runs-on: ubuntu-latest
    needs: test-push
    steps:
      - name: Comentário
        run: |
          echo "Comentário DEPENDENCY WORKFLOW"

  test-push-3:
    runs-on: ubuntu-latest
    needs: test-push-2
    steps:
      - name: Comentário
        run: |
          echo "Comentário DEPENDENCY WORKFLOW"
