name: GitHub Actions - Push General
run-name: Running - ${{ github.event_name }}
on:
  push:
    branches:
      - main
      - develop
    # branches-ignore:
    # - 'release/**'
    # paths:
    #   - "**.txt"
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário PUSH WORKFLOW"
      - name: Comentário variable
        run: |
          echo "Comentário VAR: ${{ vars.VAR_TESTE }}"
      - name: Comentário secret
        run: |
          echo "Comentário SECRET: ${{ secrets.SECRET_TESTE }}"
