name: GitHub Actions - Trigger 1
run-name: Running - Trigger 1
on:
  push:
    branches:
      - main
      - develop
    # branches-ignore:
    # - 'release/**'
    paths:
      - "**.txt"
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Trigger finalizado"
